#services:
#    Landlib\SymfonyToolsBundle\Service\FileUploaderService:
#        arguments: ["@service_container"]
#        class: Landlib\SymfonyToolsBundle\Service\FileUploaderService

#        #class: FOS\UserBundle\Controller\ChangePasswordController
#        #arguments: ["@service_container", "@doctrine"]


rupayservices.yacache: "%env(resolve:YANDEX_CACHE)%"
rupayservices.yasecretkey: "%env(resolve:YANDEX_SECRET_KEY)%"
#all entity classes set here
rupayservices.defaultPayTransactionEntity: Landlib\SymfonyRuPaymentsServices\Entity\PhdPayTransaction

#Код операции, которая записывается в operations по умолчанию при успешной оплате
rupayservices.operation_code_id: 4;


# Массив дробных чисел. Допустимые к вводу суммы. Если не пуст, при создании транзакции выполняется валидация
rupayservices.a_fixed_sum: []


app.qiwi_phone: "%env(resolve:QIWI_PHONE)%"
app.qiwi_public_key: "%env(resolve:QIWI_PUBLIC_KEY)%"
app.qiwi_secret_key: "%env(resolve:QIWI_SECRET_KEY)%"

